version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_test
    ports:
      - "5673:5672"
      - "15672:15672"
    volumes:
      - data:/var/lib/rabbitmq_test
      - log:/var/log/rabbitmq_test
      # - ./data:/var/lib/rabbitmq # saving data in data folder in current project
      # - ./log:/var/log/rabbitmq # saving log in data log in current project
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      TZ: "Asia/Kolkata"
volumes:
  data:
  log: